# Config file for automatic testing at travis-ci.org

sudo: false

addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
matrix:
  fast_finish: true
  include:
  - python: 3.5
    env: TOXENV=docs
  - python: 3.5
    env: TOXENV=quality-check

install:
  - pip install tox tox-travis
  - pip install coveralls
script: tox
after_success:
  - if [[ $TOX_ENV == "quality-check" ]]; then
      coveralls;
    fi

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
